spring:
  application:
    name: discovery-cluster

---
spring:
  profiles: discovery1
server:
  port: 8761
eureka:
  instance:
    hostname: discovery1
    preferIpAddress: true
  client:
    service-url:
      default-zone: http://${eureka.instance.hostname}:8762/eureka
    register-with-eureka: false
    fetch-registry: false

---
spring:
  profiles: discovery2
server:
  port: 8762
eureka:
  instance:
    hostname: discovery2
    preferIpAddress: true
  client:
    service-url:
      default-zone: http://${eureka.instance.hostname}:8761/eureka
    register-with-eureka: false
    fetch-registry: false
