spring:
  application:
    name: discovery-cluster
---
spring:
  profiles: discovery1
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    service-url:
      default-zone: http://${eureka.instance.hostname}:8762/eureka

---
spring:
  profiles: discovery2
server:
  port: 8762
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    service-url:
      default-zone: http://${eureka.instance.hostname}:8761/eureka
