spring:
  application:
    name: gateway-app
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8000
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: asset-app
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            interruptOnTimeout: false
    fallback:
      enabled: false
    circuitBreaker:
      enabled: false
