spring:
  application:
    name: WapFrontDemo
  thymeleaf:
    cache: false
    content-type: text/xml
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8000

redis:
  sentinel: false
  masterName: resque
  maxIdle: 200
  maxTotal: 2048
  maxWaitMillis: 1000
  hosts: 127.0.0.1:6379
  db: 0
  password:

