spring:
  application:
    name: gateway-app
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8000
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: asset-app
    api-b:
      path: /api-b/**
      serviceId: integral-app
  host:
    max-per-route-connections: 2000
    max-total-connections: 20000
    socket-timeout-millis: 60000
    connect-timeout-millis: 25000
  semaphore:
    max-semaphores: 3000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 60000

